# Generated by Django 5.2.14 on 2026-05-16 12:15

import django.db.models.deletion
import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cidr', netfields.fields.CidrAddressField(max_length=43, unique=True)),
                ('ip_version', models.PositiveSmallIntegerField(editable=False)),
                ('block_prefix', models.PositiveSmallIntegerField(blank=True, help_text='IPv4 only: prefix length of one grid cell, e.g. 30', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['cidr'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', netfields.fields.CidrAddressField(max_length=43)),
                ('gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='ipam.customer')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='ipam.pool')),
            ],
            options={
                'ordering': ['cidr'],
            },
        ),
    ]
